
phases:

- phase: 'TestInUbuntu'
  queue:
    name: 'Hosted Linux Preview'
    parallel: 1
    matrix:
      # Python27:
      #   python.version: '2.7'
      # Python35:
      #   python.version: '3.5'
      Python36:
        conda: true
        python.version: '3.6'
        numpy.version: '1.14.2'
        scipy.version: '1.0.0'
        pandas.version: '0.20.3'
        cython.version: '0.26.1'
        pyamg.version: '3.3.2'
        pillow.version: '4.3.0'
        coverage: true
        run_flake8: false
        check_pytest_soft_dependency: true
        test_docstrings: true
      # Python37-dev:
      #   python.version: '>= 3.7.0a'
  
  variables:
    test_dir: '$($BUILD_BINARIESDIRECTORY/test)'
    omp_num_threads: 4
    openblas_num_threads: 4

  steps:

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
        architecture: 'x64'

    - script: ./build_tools/vsts/conda.sh
      displayName: 'Conda'
      condition: eq(variables['conda'], true)

    - script: ./build_tools/vsts/tools.sh
      displayName: 'Install tools'
      condition: or(eq(variables['coverage'], true), eq(variables['run_flake8'], true), eq(variables['test_docstrings'], true))

    - script: ./build_tools/vsts/build.sh
      displayName: 'Build'
    
    - script: ./build_tools/vsts/test.sh
      displayName: 'Test'
    
    - script: ./build_tools/vsts/codecov.sh
      displayName: 'Codecov prepare and upload'

    - task: PublishCodeCoverageResults@1
      displayName: 'Publish code coverage results'
      inputs:
        summaryFileLocation: 'coverage.xml'
        codeCoverageTool: 'cobertura'

